### ISSUE TITLE
Enhancement - login script for file association

### ISSUE THREAD

**Issue by tgoggans** [operepo/ope_laptop_binaries#3]
Login script desired to associate file types with apps that function when user group policies are applied on laptops. Some apps are restricted and a GP login script to associate video and image files with apps that are not restricted by existing group policies would be beneficial.

**Comment by jmichel-sbctc** [comment]
There is a new feature in the credential app that allows the user to apply additional GP changes both before and after the original GP policies. To utilize the feature you need to set your group policy and then do the following.

1. run 'mgmt export_group_policy'
2. navigate to C:\ProgramData\ope\Services\mgmt\rc\exported_gpo
3. Cut the folder that was created by the first command
4. Paste into the preferred gp folder at C:\ProgramData\ope\Services\mgmt\rc\ (gpo_pre or gpo_post)
5. If these folders don't exist, create them. Also you can only have one GP folder in them, additional ones will cause a failure.

I'll be working on documentation on this so that this feature is easier to utilize.
